default[:raven_db][:local_dir] = "/opt/local_db"
default[:raven_db][:memcached_port] = "11211"
default[:raven_db][:memcached_user] = "memcached"
default[:raven_db][:memcached_max_conn] = "4096"
default[:raven_db][:memcached_max_mem] = "900"
default[:raven_db][:memcached_socket] = ""
